version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  kafka-example:
    build:
      context: .
      target: development
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
