version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  kafka-example:
    build:
      context: .
      target: development
    depends_on: 
      - kafka
      - zookeeper
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "Topic1:1:1"
